name: simple_tiles_map
description: Crea fondos de mapa de OpenStreetMap, google, Stamen, CartoMap,
  Esri de forma sencilla con soporte offline.
repository: https://github.com/danielquisbert/simple_tiles_map
version: 3.0.0
homepage: https://danielquisbert.github.io

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_map_tile_caching: ^10.1.1
  latlong2: ^0.9.1

dev_dependencies:
  analyzer: ^6.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
